export const TEMPLATE_CONFIG = [
  // --- CREATIVE ---
  {
    id: "CreativePulse",
    name: "Creative Pulse",
    componentName: "ModernDark",
    category: "Creative",
    role: ["Diseño Gráfico", "Branding", "Multimedia"],
    level: "Mid/Senior",
    design_identity: "Layout asimétrico",
    description: "Secciones visuales, cards creativas. Creatividad con estructura profesional.",
    industry: "Creative",
    keywords: ["Branding", "Visual Identity", "Art Direction", "Creativity"],
    recruiter_focus: "Portfolio & Style",
    ats_score: "Medium",
    layout_type: "dark",
    content_style: "Narrative",
    tags: ["creative", "design", "branding", "portfolio"],
    badge: "Impacto Visual",
    badgeColor: "bg-rose-500",
    fonts: { title: "Poppins", body: "Inter" },
    colors: { primary: "Blanco", secondary: "Gris suave", accent: "Coral/Violeta" },
    colorHex: { primary: "#ffffff", secondary: "#f1f5f9", accent: "#f43f5e" }
  },
  {
    id: "UXFlow",
    name: "UX Flow",
    componentName: "SwissGrid",
    category: "Creative",
    role: "UX/UI",
    level: "Senior",
    design_identity: "Timeline de procesos",
    description: "Secciones tipo case study. Enfoque en User Research, Wireframes.",
    industry: "Creative",
    keywords: ["User Research", "Wireframes", "Usability", "Prototyping"],
    recruiter_focus: "Process & Methodology",
    ats_score: "Medium/High",
    layout_type: "sidebar",
    content_style: "Case Study",
    tags: ["creative", "ux-ui", "product", "process"],
    badge: "Especial UX/UI",
    badgeColor: "bg-indigo-500",
    fonts: { title: "DM Sans", body: "Inter" },
    colors: { primary: "Azul suave", secondary: "Lila", accent: "Fondos claros" },
    colorHex: { primary: "#eff6ff", secondary: "#a78bfa", accent: "#60a5fa" }
  },
  {
    id: "FashionForm",
    name: "Fashion Form",
    componentName: "IvyLeague",
    category: "Creative",
    role: "Fashion",
    level: "Junior/Mid",
    design_identity: "Editorial tipo revista",
    description: "Espacios amplios, tipografía editorial. Ideal para Fashion Design, Styling.",
    industry: "Fashion",
    keywords: ["Fashion Design", "Collection", "Styling", "Trends"],
    recruiter_focus: "Aesthetic & Collection",
    ats_score: "Medium",
    layout_type: "serif",
    content_style: "Elegant",
    tags: ["creative", "fashion", "editorial", "style"],
    badge: "Editorial Mode",
    badgeColor: "bg-zinc-800",
    fonts: { title: "Playfair Display", body: "Lato" },
    colors: { primary: "Negro", secondary: "Blanco/Beige", accent: "Dorado suave" },
    colorHex: { primary: "#000000", secondary: "#fdfbf7", accent: "#d4af37" }
  },
  {
    id: "ShowcasePro",
    name: "Showcase Pro",
    componentName: "TechGamer",
    category: "Creative",
    role: ["Creative", "Frontend", "UX"],
    level: "Any",
    design_identity: "CV + Galería visual",
    description: "CV con mini previews de proyectos. Ideal para perfiles visuales.",
    industry: "Creative",
    keywords: ["Portfolio", "Gallery", "Projects", "Visuals"],
    recruiter_focus: "Visual Proof",
    ats_score: "Medium",
    layout_type: "grid",
    content_style: "Visual",
    tags: ["creative", "portfolio", "gallery"],
    badge: "Galería Integrada",
    badgeColor: "bg-orange-500",
    fonts: { title: "Manrope", body: "Inter" },
    colors: { primary: "Blanco", secondary: "Gris", accent: "Personalizado" },
    colorHex: { primary: "#ffffff", secondary: "#e5e7eb", accent: "#f97316" }
  },

  // --- TECH ---
  {
    id: "FrontendVision",
    name: "Frontend Vision",
    componentName: "TechGamer",
    category: "Tech",
    role: "Frontend",
    level: "Mid/Senior",
    design_identity: "Grid moderno",
    description: "Grid moderno, stack visible con chips. Ideal para React, TypeScript, UI.",
    industry: "Tech",
    keywords: ["React", "TypeScript", "UI", "Performance"],
    recruiter_focus: "Technical Skills & Projects",
    ats_score: "High",
    layout_type: "grid",
    content_style: "Technical",
    tags: ["tech", "frontend", "modern", "portfolio"],
    badge: "Más usado en Frontend",
    badgeColor: "bg-blue-600",
    fonts: { title: "Inter", body: "JetBrains Mono" },
    colors: { primary: "Azul eléctrico", secondary: "Blanco", accent: "Turquesa" },
    colorHex: { primary: "#2563eb", secondary: "#ffffff", accent: "#06b6d4" }
  },
  {
    id: "BackendCore",
    name: "Backend Core",
    componentName: "MinimalWhite",
    category: "Tech",
    role: "Backend",
    level: "Senior",
    design_identity: "Arquitectura clara",
    description: "Columna única, bloques técnicos. Ideal para APIs, Microservices, Cloud.",
    industry: "Tech",
    keywords: ["APIs", "Microservices", "Cloud", "Databases"],
    recruiter_focus: "Architecture & Stability",
    ats_score: "Very High",
    layout_type: "minimal",
    content_style: "Concise",
    tags: ["tech", "backend", "ats", "minimal"],
    badge: "Optimizado Backend",
    badgeColor: "bg-emerald-600",
    fonts: { title: "IBM Plex Sans", body: "Inter" },
    colors: { primary: "Gris oscuro", secondary: "Verde técnico", accent: "Neutro" },
    colorHex: { primary: "#1e293b", secondary: "#10b981", accent: "#10b981" }
  },
  {
    id: "HybridPro",
    name: "Hybrid Pro",
    componentName: "TechGamer",
    category: "Tech",
    role: ["Frontend", "UX", "Full Stack"],
    level: "Mid/Senior",
    design_identity: "CV ATS + Visual",
    description: "Estructura híbrida: CV ATS compatible + sección visual de proyectos.",
    industry: "Tech",
    keywords: ["Hybrid", "Design", "Development", "Portfolio"],
    recruiter_focus: "Versatility",
    ats_score: "High",
    layout_type: "grid",
    content_style: "Hybrid",
    tags: ["tech", "hybrid", "creative", "portfolio"],
    badge: "Híbrido ATS + Visual",
    badgeColor: "bg-violet-600",
    fonts: { title: "Inter", body: "Inter" },
    colors: { primary: "Base neutra", secondary: "Acentos dinámicos", accent: "Dynamic" },
    colorHex: { primary: "#f3f4f6", secondary: "#8b5cf6", accent: "#8b5cf6" }
  },

  // --- GENERAL / LEVEL ---
  {
    id: "ATSSmart",
    name: "ATS Smart",
    componentName: "MinimalWhite",
    category: "General",
    role: "Any",
    level: "Any",
    design_identity: "Ultra limpio",
    description: "Una columna, sin íconos. Máximo match con sistemas ATS.",
    industry: "General",
    keywords: ["ATS", "Optimization", "Clean", "Standard"],
    recruiter_focus: "Readability & Parsing",
    ats_score: "Max",
    layout_type: "minimal",
    content_style: "Standard",
    tags: ["ats", "clean", "minimal", "general"],
    badge: "100% ATS Friendly",
    badgeColor: "bg-slate-700",
    fonts: { title: "Arial", body: "Calibri" },
    colors: { primary: "Blanco", secondary: "Negro", accent: "None" },
    colorHex: { primary: "#ffffff", secondary: "#000000", accent: "#334155" }
  },
  {
    id: "SmartStart",
    name: "Smart Start",
    componentName: "CorporateBlue",
    category: "General",
    role: "Junior",
    level: "Junior",
    design_identity: "Visual ligero",
    description: "Enfoque en habilidades y crecimiento. Ideal para primeros empleos.",
    industry: "General",
    keywords: ["Learning", "Skills", "Projects", "Growth"],
    recruiter_focus: "Potential & Soft Skills",
    ats_score: "High",
    layout_type: "accent",
    content_style: "Growth-oriented",
    tags: ["junior", "entry-level", "skills"],
    badge: "Ideal Junior",
    badgeColor: "bg-teal-500",
    fonts: { title: "Nunito", body: "Inter" },
    colors: { primary: "Azul claro", secondary: "Verde suave", accent: "Fresh" },
    colorHex: { primary: "#bae6fd", secondary: "#86efac", accent: "#0ea5e9" }
  },
  {
    id: "SeniorPrestige",
    name: "Senior Prestige",
    componentName: "ExecutiveGray",
    category: "General",
    role: "Senior",
    level: "Senior",
    design_identity: "Logros arriba",
    description: "Métricas visibles, enfoque en resultados. Experiencia y liderazgo.",
    industry: "General",
    keywords: ["Experience", "Results", "Leadership", "Impact"],
    recruiter_focus: "Impact & Metrics",
    ats_score: "High",
    layout_type: "header-blue",
    content_style: "Results-driven",
    tags: ["senior", "management", "results"],
    badge: "Alto Impacto",
    badgeColor: "bg-blue-800",
    fonts: { title: "Montserrat", body: "Inter" },
    colors: { primary: "Azul oscuro", secondary: "Gris", accent: "Professional" },
    colorHex: { primary: "#1e3a8a", secondary: "#4b5563", accent: "#1e3a8a" }
  },
  {
    id: "LeadershipPrime",
    name: "Leadership Prime",
    componentName: "ExecutiveGray",
    category: "General",
    role: "Lead",
    level: "Lead",
    design_identity: "Ejecutivo",
    description: "Resumen estratégico, estilo sobrio. Para Tech Lead, Manager, CTO.",
    industry: "General",
    keywords: ["Leadership", "Strategy", "Team Management", "Vision"],
    recruiter_focus: "Strategy & Leadership",
    ats_score: "High",
    layout_type: "header-blue",
    content_style: "Executive",
    tags: ["lead", "executive", "strategy", "management"],
    badge: "Nivel Ejecutivo",
    badgeColor: "bg-slate-900",
    fonts: { title: "Source Serif Pro", body: "Inter" },
    colors: { primary: "Negro", secondary: "Azul marino", accent: "Sobrio" },
    colorHex: { primary: "#000000", secondary: "#0f172a", accent: "#0f172a" }
  }
];
